using DidComm.Facade;
using DidComm.Messages;
using DidComm.Protocols.Rotation;

namespace DidComm.Samples.Cookbook.Sections;

/// <summary>
/// PRD §14.2 — <strong>N. DID rotation (<c>from_prior</c> — FR-ROT-*)</strong>.
/// Alice rotates from her original peer DID to <c>alice2</c>. The first message Bob receives
/// from <c>alice2</c> carries a <c>from_prior</c> JWT signed by Alice's original
/// authentication key — proving the rotation. Bob's unpack populates
/// <see cref="UnpackResult.FromPrior"/>.
/// </summary>
public static class Section_N_FromPriorRotation
{
    /// <summary>Run this section against the shared <see cref="CookbookContext"/>.</summary>
    /// <param name="ctx">The shared cookbook context.</param>
    public static async Task RunAsync(CookbookContext ctx)
    {
        ctx.Narrator.Section("N", "DID rotation (from_prior — FR-ROT-*)");

        // Pick alice's authentication private (Ed25519, the second key generated by PeerIdentityFactory).
        var alicePriorAuthKey = ctx.Alice.Privates.First(k => string.Equals(k.Crv, "Ed25519", StringComparison.Ordinal));

        var claims = new FromPriorClaims(
            Sub: ctx.Alice2.Did,
            Iss: ctx.Alice.Did,
            Iat: DateTimeOffset.UtcNow.ToUnixTimeSeconds());

        ctx.Narrator.Step("Build from_prior JWT signed by alice's prior authentication key.");
        var jwt = FromPriorBuilder.Build(claims, alicePriorAuthKey);
        ctx.Narrator.Value("jwt.length", jwt.Length);
        ctx.Narrator.Value("jwt.head", jwt[..Math.Min(60, jwt.Length)] + "…");

        var rotationMessage = new MessageBuilder()
            .WithType("https://didcomm.org/basicmessage/2.0/message")
            .WithFrom(ctx.Alice2.Did)
            .WithTo(ctx.Bob.Did)
            .WithFromPrior(jwt)
            .Build();

        ctx.Narrator.Step("Pack as authcrypt(alice2 → bob) — FR-ROT-03 requires rotation messages be encrypted.");
        var packed = await ctx.Client.PackEncryptedAsync(rotationMessage, new PackEncryptedOptions(
            Recipients: new[] { ctx.Bob.Did },
            From: ctx.Alice2.Did));

        ctx.Narrator.Step("Unpack as bob.");
        var result = await ctx.Client.UnpackAsync(packed);

        ctx.Narrator.Value("FromPrior.Sub", result.FromPrior?.Sub);
        ctx.Narrator.Value("FromPrior.Iss", result.FromPrior?.Iss);
        ctx.Narrator.Value("FromPrior.Iat", result.FromPrior?.Iat);
        ctx.Narrator.Value("Sub == message.From", result.FromPrior?.Sub == result.Message.From);

        ctx.Narrator.Step("FR-ROT-03 demo: PackPlaintextAsync with from_prior must throw.");
        try
        {
            var unwrappedAttempt = new MessageBuilder()
                .WithType("https://didcomm.org/basicmessage/2.0/message")
                .WithFrom(ctx.Alice2.Did)
                .WithFromPrior(jwt)
                .Build();
            _ = await ctx.Client.PackPlaintextAsync(unwrappedAttempt);
            ctx.Narrator.Note("UNEXPECTED — PackPlaintextAsync did not throw.");
        }
        catch (InvalidOperationException ex)
        {
            ctx.Narrator.Note(ex.Message);
        }
    }
}
